# Generated by Django 4.0.4 on 2022-05-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eBook', '0003_alter_mark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='eBook.student'),
        ),
    ]
